### ISSUE TITLE
sodar ingest error with quality column

### ISSUE THREAD

**Issue by akrherz** [akrherz/talltowers#7]
An error from the automation
```
process_sodar reading /home/sodar/triton_963_2019-04-14-05-30_extended.csv resulted in exp [Errno 2] File b'/home/sodar/triton_963_2019-04-14-05-30_extended.csv' does not exist: b'/home/sodar/triton_963_2019-04-14-05-30_extended.csv'
process_sodar reading /home/sodar/triton_963_2019-04-14-05-30_operational.csv resulted in exp [Errno 2] File b'/home/sodar/triton_963_2019-04-14-05-30_operational.csv' does not exist: b'/home/sodar/triton_963_2019-04-14-05-30_operational.csv'
Traceback (most recent call last):
  File "process_sodar.py", line 176, in <module>
    main(sys.argv)
  File "process_sodar.py", line 172, in main
    ingest(valid2)
  File "process_sodar.py", line 128, in ingest
    dbsave(profile2, valid)
  File "process_sodar.py", line 52, in dbsave
    """, args)
psycopg2.ProgrammingError: column "quality" of relation "sodar_surface" does not exist
LINE 2: ...          INSERT into sodar_surface(station,valid,quality,wi...
```

**Comment by akrherz** [comment]
This is just bad logic when we don't have a three file quorum.
